# site name
siteName: 安南说
shortName: 说


# full https model which means #Content-Security-Policy = upgrade-insecure-requests# in meat tag
fullHttps: true

# favicon
favicon: /favicon.ico
# unique avatar
avatarShow: false
avatarImage: /favicon.ico

# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number
homeArticleShown: 10


# your site build time or domain buy time
siteBuildingTime: 01/20/2018


# Top navigate menu name
## Notice:
## Name order decide show index.The name also called category alias,so you must set category alias before start server.
## BTW,'category_map' and 'tag_map' field in site '_config.yml' file must one to one correspondence with menus below.
menu:
   编程: programing
   人文: humanities
   其他: others

# Left menu of single pages settings
## Notice: faName is FontAwesome style name
leftPagesMenu:
- uri: help
  title: 帮助
  faName: fa-question-circle


# cover info config
coverTitle: 你我的余生都在这里!
coverDescription: 不把生命献给无知、平庸和低俗!

# sns url
sns:
  telegram: http://t.me/jiusanzhou
  instagram: https://www.instagram.com/jiusanzhou/
  twitter: https://twitter.com/jiusanzhou
  github: https://github.com/jiusanzhou

# your article copyright or content declare
postDeclare: 本文内容与「好好工作」出品无关。本文代表个人观点，内容仅供参考。若有不恰当之处，望不吝赐教！

# Git-pages server info
pageServerName: Coding
pageServerUrl: https://coding.net/register?key=bcace447-fa41-4579-9783-86fdf0f723e2


# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: false
  githubID:
  repo:
  ClientID:
  ClientSecret:
  lazy: true

## Comments settings.You can choose only ONE to display.
# disqus shortName
disqus_shortname:

# Analytics
tentcentAnalyticsId:
googleAnalyticsId:
